### ISSUE TITLE
Error running http.kafka.oneway from zilla-examples

### ISSUE THREAD

**Issue by attilakreiner** [aklivity/zilla#117]
**Describe the bug**
I followed the instructions in the `http.kafka.oneway/README.md` [file](https://github.com/aklivity/zilla-examples/blob/e3beb1eae6e338f93ada5105e1486ea7d02e8d95/http.kafka.oneway/README.md) in the [zilla-examples](https://github.com/aklivity/zilla-examples) repository and ran into an error.

**To Reproduce**
1. Go to https://github.com/aklivity/zilla-examples/blob/e3beb1eae6e338f93ada5105e1486ea7d02e8d95/http.kafka.oneway/README.md and follow the instructions there
2. At the **Verify behavior** step I got an error with this stack trace when sending the `POST` request with `curl`:
```
org.agrona.concurrent.AgentTerminationException: java.lang.NullPointerException: Cannot invoke "io.aklivity.zilla.runtime.binding.kafka.internal.types.stream.KafkaDataExFW.merged()" because "kafkaDataEx" is null
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:572)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "io.aklivity.zilla.runtime.binding.kafka.internal.types.stream.KafkaDataExFW.merged()" because "kafkaDataEx" is null
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaMergedFactory$KafkaUnmergedProduceStream.doProduceInitialData(KafkaMergedFactory.java:2818)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaMergedFactory$KafkaMergedStream.onMergedInitialData(KafkaMergedFactory.java:1142)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaMergedFactory$KafkaMergedStream.onMergedMessage(KafkaMergedFactory.java:1033)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaMergedFactory.lambda$newStream$4(KafkaMergedFactory.java:228)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:988)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:953)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:566)
	... 3 more
	Suppressed: java.lang.Exception: [engine/data#3]	[0x0303000000000007] streams=[consumeAt=0x00001658 (0x0000000000001658), produceAt=0x00001770 (0x0000000000001770)]
		at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:570)
		... 3 more
stopped
```

**Expected behavior**
The `curl` command in the instructions should work well.

**Desktop:**
 - OS: macOS Big Sur 11.6.8

**Comment by jfallows** [comment]
@attilakreiner thanks!

This looks legit, an NPE caused by no `KafkaMergedDataEx` present on the `DATA` frame coming from `http-kafka` for oneway message.

**Comment by attilakreiner** [comment]
I am looking into this to find a fix.

**Comment by attilakreiner** [comment]
I created a draft PR for the fix: https://github.com/aklivity/zilla/pull/120

Still need to look into the integration tests.
