### ISSUE TITLE
Zilla dump IndexOutOfBoundException when continuously recording packets at Zilla run

### ISSUE THREAD

**Issue by bmaidics** [aklivity/zilla#1224]
**Describe the bug**
Zilla dump crashes with IndexOutOfBoundException when continuously recording packets at while Zilla runs in the background.
**To Reproduce**
1. Start zilla
2. Start zilla dump: `./zilla dump -v -e -Pzilla.engine.directory=<your-zilla-engine dir> -w debug.pcap`
3. See error (you might need to run it a couple of times)

Logs:

```
java.lang.IndexOutOfBoundsException: limit=10312404 is beyond maxLimit=10312375
        at io.aklivity.zilla.runtime.command.dump/io.aklivity.zilla.runtime.command.dump.internal.types.Flyweight.checkLimit(Flyweight.java:67)
        at io.aklivity.zilla.runtime.command.dump/io.aklivity.zilla.runtime.command.dump.internal.types.stream.FrameFW.wrap(FrameFW.java:85)
        at io.aklivity.zilla.runtime.command.dump/io.aklivity.zilla.runtime.command.dump.internal.airline.ZillaDumpCommand.lambda$run$3(ZillaDumpCommand.java:345)
        at io.aklivity.zilla.runtime.command.dump/io.aklivity.zilla.runtime.command.dump.internal.airline.spy.OneToOneRingBufferSpy.peek(OneToOneRingBufferSpy.java:166)
        at io.aklivity.zilla.runtime.command.dump/io.aklivity.zilla.runtime.command.dump.internal.airline.ZillaDumpCommand.run(ZillaDumpCommand.java:343)
        at io.aklivity.zilla.runtime.command/io.aklivity.zilla.runtime.command.internal.ZillaMain$Invoker.invoke(ZillaMain.java:69)
        at io.aklivity.zilla.runtime.command/io.aklivity.zilla.runtime.command.internal.ZillaMain.invoke(ZillaMain.java:40)
        at io.aklivity.zilla.runtime.command/io.aklivity.zilla.runtime.command.internal.ZillaMain.main(ZillaMain.java:34)

```

**Comment by jfallows** [comment]
This can happen if `zilla dump` cannot keep up with `zilla` without being "lapped" in one or more of the ring buffers.
