### ISSUE TITLE
Malformed if-match value triggers exception

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla#38]
### Steps to reproduce:

1. Binding config
```
"http_kafka_proxy0":

        {
            "type" : "http-kafka",
            "kind": "proxy",
            "routes":
            [
                {
                    "when":
                    [
                        {
                            "method": "PUT",
                            "path": "/items/{id}"
                        },
                       "with":
                      {
                          "capability": "produce",
                          "topic": "items-commands",
                          "key": "${params.id}",
                          "reply-to": "item-replies"
                      }
                        .....
```
2. Curl command:

```
curl -v \
    -X "PUT" "http://localhost:8080/items/9417E83E-313E-468E-AC7C-1BCE0BAF9712" \
    -H "Idempotency-Key: `uuidgen`" \
    -H "Content-Type: application/json" \
    -H "If-Match: wrong" \
    -d "{\"@type\": \"UpdateItemCommand\", \"description\": \"Test1\"}"
```

**Exception:**

```
org.agrona.concurrent.AgentTerminationException: java.lang.IllegalArgumentException: negative length: -1

at io.aklivity.zilla.runtime.engine@0.9.17/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:572)

at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)

at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)

at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: java.lang.IllegalArgumentException: negative length: -1

at org.agrona.core/org.agrona.concurrent.UnsafeBuffer.lengthCheck(UnsafeBuffer.java:1705)

at org.agrona.core/org.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:944)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.types.OctetsFW$Builder.set(OctetsFW.java:77)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.types.KafkaHeaderFW$Builder.value(KafkaHeaderFW.java:256)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.config.HttpKafkaWithProduceResult.lambda$header$3(HttpKafkaWithProduceResult.java:168)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.types.Array32FW$Builder.item(Array32FW.java:192)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.config.HttpKafkaWithProduceResult.header(HttpKafkaWithProduceResult.java:164)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.config.HttpKafkaWithProduceResult.lambda$headers$1(HttpKafkaWithProduceResult.java:131)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.types.Array32FW.forEach(Array32FW.java:68)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.config.HttpKafkaWithProduceResult.headers(HttpKafkaWithProduceResult.java:131)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.stream.HttpKafkaProxyFactory$HttpProduceSyncProxy.lambda$onHttpBegin$2(HttpKafkaProxyFactory.java:3179)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.types.stream.KafkaMergedDataExFW$Builder.headers(KafkaMergedDataExFW.java:300)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.stream.HttpKafkaProxyFactory$HttpProduceSyncProxy.lambda$onHttpBegin$3(HttpKafkaProxyFactory.java:3179)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.types.stream.KafkaDataExFW$Builder.merged(KafkaDataExFW.java:265)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.stream.HttpKafkaProxyFactory$HttpProduceSyncProxy.onHttpBegin(HttpKafkaProxyFactory.java:3174)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.stream.HttpKafkaProxyFactory$HttpProduceSyncProxy.onHttpMessage(HttpKafkaProxyFactory.java:3106)

at io.aklivity.zilla.runtime.binding.http.kafka@0.9.17/io.aklivity.zilla.runtime.binding.http.kafka.internal.stream.HttpKafkaProxyFactory.lambda$newStream$4(HttpKafkaProxyFactory.java:224)

at io.aklivity.zilla.runtime.engine@0.9.17/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleDefaultReadInitial(DispatchAgent.java:1073)

at io.aklivity.zilla.runtime.engine@0.9.17/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1010)

at io.aklivity.zilla.runtime.engine@0.9.17/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:953)

at io.aklivity.zilla.runtime.engine@0.9.17/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)

at io.aklivity.zilla.runtime.engine@0.9.17/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:566)
```

**Comment by jfallows** [comment]
This seems to be caused by `if-match` containing no `etag` after a trailing `/` so value is `null` and still attempting to propagate as a Kafka message header.
