### ISSUE TITLE
Ws to tls proxy misinterprets begin extension 

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla#63]
```
org.agrona.concurrent.AgentTerminationException: java.lang.NullPointerException: Cannot invoke "io.aklivity.zilla.runtime.binding.tcp.internal.types.ProxyAddressFamily.ordinal()" because the return value of "io.aklivity.zilla.runtime.binding.tcp.internal.types.ProxyAddressFW.kind()" is null
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:572)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "io.aklivity.zilla.runtime.binding.tcp.internal.types.ProxyAddressFamily.ordinal()" because the return value of "io.aklivity.zilla.runtime.binding.tcp.internal.types.ProxyAddressFW.kind()" is null
	at io.aklivity.zilla.runtime.binding.tcp/io.aklivity.zilla.runtime.binding.tcp.internal.types.ProxyAddressFW.tryWrap(ProxyAddressFW.java:79)
	at io.aklivity.zilla.runtime.binding.tcp/io.aklivity.zilla.runtime.binding.tcp.internal.types.stream.ProxyBeginExFW.tryWrap(ProxyBeginExFW.java:52)
	at io.aklivity.zilla.runtime.binding.tcp/io.aklivity.zilla.runtime.binding.tcp.internal.types.OctetsFW.get(OctetsFW.java:15)
	at io.aklivity.zilla.runtime.binding.tcp/io.aklivity.zilla.runtime.binding.tcp.internal.stream.TcpClientFactory.newStream(TcpClientFactory.java:130)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleBeginInitial(DispatchAgent.java:1278)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleDefaultReadInitial(DispatchAgent.java:1070)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1010)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:953)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:566)
	... 3 more
	Suppressed: java.lang.Exception: [engine/data#9]	[0x0909000000000009] streams=[consumeAt=0x000005c8 (0x00000000000005c8), produceAt=0x000005c8 (0x00000000000005c8)]
		at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:570)
		... 3 more
```

**Comment by jfallows** [comment]
Thanks @akrambek !

Looks like the `tls` binding is propagating the extension metadata from `ws` and `tcp` is failing to wrap the bytes.
We need to add a check for the extension type id before wrapping in `tcp`, and also before propagating in `tls.`
