### ISSUE TITLE
Flaky kafka-grpc test

### ISSUE THREAD

**Issue by bmaidics** [aklivity/zilla#768]
Some Kafka-grpc tests are failing intermittently .

```
[INFO] Running io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerIT
org.agrona.concurrent.AgentTerminationException: java.lang.IllegalStateException: missing file for streams : /home/runner/work/zilla/zilla/runtime/binding-kafka-grpc/target/zilla-itests/data63
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:707)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: missing file for streams : /home/runner/work/zilla/zilla/runtime/binding-kafka-grpc/target/zilla-itests/data63
	at org.agrona.IoUtil.checkFileExists(IoUtil.java:507)
	at org.agrona.IoUtil.mapExistingFile(IoUtil.java:396)
	at org.agrona.IoUtil.mapExistingFile(IoUtil.java:361)
	at io.aklivity.zilla.runtime.engine.internal.layouts.StreamsLayout$Builder.build(StreamsLayout.java:105)
	at io.aklivity.zilla.runtime.engine.internal.stream.Target.<init>(Target.java:85)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.newTarget(EngineWorker.java:1611)
	at org.agrona.collections.Int2ObjectHashMap.computeIfAbsent(Int2ObjectHashMap.java:268)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.supplyTarget(EngineWorker.java:1544)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.supplyWriter(EngineWorker.java:1538)
	at org.agrona.collections.Int2ObjectHashMap.computeIfAbsent(Int2ObjectHashMap.java:268)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.supplyReceiver(EngineWorker.java:1532)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.newStream(EngineWorker.java:1516)
	at io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerFactory.newKafkaFetch(KafkaGrpcRemoteServerFactory.java:2092)
	at io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerFactory$KafkaRemoteServer.doKafkaBegin(KafkaGrpcRemoteServerFactory.java:310)
	at io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerFactory$KafkaRemoteServer.initiate(KafkaGrpcRemoteServerFactory.java:287)
	at io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerFactory.lambda$onKafkaStreamInitializationSignal$5(KafkaGrpcRemoteServerFactory.java:2005)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerFactory.onKafkaStreamInitializationSignal(KafkaGrpcRemoteServerFactory.java:2005)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker$ElektronSignaler.lambda$signalAt$1(EngineWorker.java:1726)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.handleExpire(EngineWorker.java:1014)
	at org.agrona.DeadlineTimerWheel.poll(DeadlineTimerWheel.java:344)
	at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:694)
	... 3 more
	Suppressed: java.lang.Exception: [engine/data#0]	[0x0000000000000000] streams=[consumeAt=0x00000060 (0x0000000000000060), produceAt=0x00000060 (0x0000000000000060)]
		at io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:705)
		... 3 more
Error:  Tests run: 4, Failures: 0, Errors: 3, Skipped: 1, Time elapsed: 1.398 s <<< FAILURE! - in io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerIT
Error:  io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders  Time elapsed: 1.328 s  <<< ERROR!
org.agrona.concurrent.AgentTerminationException: java.lang.IllegalStateException: missing file for streams : /home/runner/work/zilla/zilla/runtime/binding-kafka-grpc/target/zilla-itests/data63
Caused by: java.lang.IllegalStateException: missing file for streams : /home/runner/work/zilla/zilla/runtime/binding-kafka-grpc/target/zilla-itests/data63

Error:  io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders  Time elapsed: 1.328 s  <<< ERROR!
java.lang.InterruptedException

Error:  io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders  Time elapsed: 1.329 s  <<< ERROR!
java.lang.InterruptedException

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:  io.aklivity.zilla.runtime.binding.kafka.grpc.internal.stream.KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders
Error:    Run 1: KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders » AgentTermination
Error:    Run 2: KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders » Interrupted
Error:    Run 3: KafkaGrpcRemoteServerIT.shouldRejectOnMissingServiceAndMethodHeaders » Interrupted
[INFO] 
[INFO] 
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 1
```

**Comment by jfallows** [comment]
This has been addressed in the Engine by waiting for k3po to create `data63` for streams instead of failing on file-not-found if zilla gets there before k3po, see #915.
