### ISSUE TITLE
SEVERE: Problem adapting object of type class NamespaceConfig to interface jakarta.json.JsonObject in class class NamespaceAdapter

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#796]
**Describe the bug**
Starting zilla with the in Helm crashes with the below stack trace:

```
Problem adapting object of type class io.aklivity.zilla.runtime.engine.config.NamespaceConfig to interface jakarta.json.JsonObject in class class io.aklivity.zilla.runtime.engine.internal.config.NamespaceAdapter
error
Feb 13, 2024 5:28:25 PM org.eclipse.yasson.internal.Unmarshaller deserializeItem
SEVERE: Problem adapting object of type class io.aklivity.zilla.runtime.engine.config.NamespaceConfig to interface jakarta.json.JsonObject in class class io.aklivity.zilla.runtime.engine.internal.config.NamespaceAdapter
java.util.concurrent.ExecutionException: io.aklivity.zilla.runtime.engine.config.ConfigException: Engine configuration failed
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
    at io.aklivity.zilla.runtime.engine@0.9.68/io.aklivity.zilla.runtime.engine.Engine.start(Engine.java:240)
    at io.aklivity.zilla.runtime.command.start@0.9.68/io.aklivity.zilla.runtime.command.start.internal.airline.ZillaStartCommand.run(ZillaStartCommand.java:164)
    at io.aklivity.zilla.runtime.command@0.9.68/io.aklivity.zilla.runtime.command.internal.ZillaMain$Invoker.invoke(ZillaMain.java:69)
    at io.aklivity.zilla.runtime.command@0.9.68/io.aklivity.zilla.runtime.command.internal.ZillaMain.invoke(ZillaMain.java:40)
    at io.aklivity.zilla.runtime.command@0.9.68/io.aklivity.zilla.runtime.command.internal.ZillaMain.main(ZillaMain.java:34)
Caused by: io.aklivity.zilla.runtime.engine.config.ConfigException: Engine configuration failed
    at io.aklivity.zilla.runtime.engine@0.9.68/io.aklivity.zilla.runtime.engine.internal.registry.EngineManager.reconfigure(EngineManager.java:156)
    at io.aklivity.zilla.runtime.engine@0.9.68/io.aklivity.zilla.runtime.engine.internal.registry.FileWatcherTask.watch(FileWatcherTask.java:118)
    ... 5 more
```

**To Reproduce**
1. Download or clone the [grpc-proxy branch and folder](https://github.com/aklivity/zilla-demos/tree/grpc-proxy/grpc-proxy)
2. With an active k8s cluster run the root `./setup.sh` script to install zilla via helm
3. See error
4. Use `./teardown.sh` to uninstall zilla via helm
5. Install the same zilla.yaml config via compose
6. `cd compose`
7. Run the compose setup by using the `./setup.sh` script.
8. Zilla doesn't crash
9. Use `./teardown.sh` to uninstall zilla via compose

**Expected behavior**
Zilla shouldn't crash on startup

**Comment by jfallows** [comment]
@vordimous this looks like an issue with the setup script, trying to map in the '.proto' file.

There are some examples with `.proto` and `helm` in `zilla-examples`.

See https://github.com/aklivity/zilla-examples/blob/main/grpc.kafka.echo/setup.sh#L10

**Comment by vordimous** [comment]
Using the correct `--set-file` command fix the startup error.
