### ISSUE TITLE
Streampay `zilla` instance crashes while trying to access  `https://localhost:9090`

### ISSUE THREAD

**Issue by aDaemonThread** [aklivity/zilla#975]
**Describe the bug**
Streampay starts as expected, but crashes while trying to access `https://localhost:9090`. I was able to valid this behaviour with latest image `ghcr.io/aklivity/zilla:latest`.

**To Reproduce**
1. Follow the steps mentioned in [streampay readme](https://github.com/aDaemonThread/zilla-demos/tree/main/streampay) to start the streampay app.
2. Try accessing `https://localhost:9090`
3. `zilla` instance crashes with mentioned exception : 

```org.agrona.concurrent.AgentTerminationException: java.lang.NegativeArraySizeException: -1
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:823)
        at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NegativeArraySizeException: -1
        at io.aklivity.zilla.runtime.binding.filesystem@0.9.79/io.aklivity.zilla.runtime.binding.filesystem.internal.stream.FileSystemServerFactory$FileSystemServer.calculateTag(FileSystemServerFactory.java:388)
        at io.aklivity.zilla.runtime.binding.filesystem@0.9.79/io.aklivity.zilla.runtime.binding.filesystem.internal.stream.FileSystemServerFactory$FileSystemServer.onAppBegin(FileSystemServerFactory.java:346)
        at io.aklivity.zilla.runtime.binding.filesystem@0.9.79/io.aklivity.zilla.runtime.binding.filesystem.internal.stream.FileSystemServerFactory$FileSystemServer.onAppMessage(FileSystemServerFactory.java:297)
        at io.aklivity.zilla.runtime.binding.filesystem@0.9.79/io.aklivity.zilla.runtime.binding.filesystem.internal.stream.FileSystemServerFactory.lambda$newStream$0(FileSystemServerFactory.java:186)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.handleDefaultReadInitial(EngineWorker.java:1321)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.handleReadInitial(EngineWorker.java:1258)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.handleRead(EngineWorker.java:1205)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:817)
        ... 3 more
        Suppressed: java.lang.Exception: [engine/data#0]        [0x0000000000000021] streams=[consumeAt=0x00024700 (0x0000000000024700), produceAt=0x00034238 (0x0000000000034238)]
                at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:821)
                ... 3 more
stopped
org.agrona.concurrent.AgentTerminationException: java.lang.NullPointerException: Cannot invoke "io.aklivity.zilla.runtime.engine.binding.function.MessageConsumer.accept(int, 
org.agrona.DirectBuffer, int, int)" because "receiver" is null
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:823)
        at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "io.aklivity.zilla.runtime.engine.binding.function.MessageConsumer.accept(int, org.agrona.DirectBuffer, int, int)" because "receiver" is null
        at io.aklivity.zilla.runtime.binding.kafka@0.9.79/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaCacheBootstrapFactory.doEnd(KafkaCacheBootstrapFactory.java:273)
        at io.aklivity.zilla.runtime.binding.kafka@0.9.79/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaCacheBootstrapFactory$KafkaBootstrapMetaStream.doMetaInitialEnd(KafkaCacheBootstrapFactory.java:1176)
        at io.aklivity.zilla.runtime.binding.kafka@0.9.79/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaCacheBootstrapFactory$KafkaBootstrapMetaStream.doMetaInitialEndIfNecessary(KafkaCacheBootstrapFactory.java:1167)
        at io.aklivity.zilla.runtime.binding.kafka@0.9.79/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaCacheBootstrapFactory$KafkaBootstrapStream.onBootstrapInitialEnd(KafkaCacheBootstrapFactory.java:495)
        at io.aklivity.zilla.runtime.binding.kafka@0.9.79/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaCacheBootstrapFactory$KafkaBootstrapStream.onBootstrapInitial(KafkaCacheBootstrapFactory.java:439)
        at io.aklivity.zilla.runtime.binding.kafka@0.9.79/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaCacheBootstrapFactory.lambda$newStream$2(KafkaCacheBootstrapFactory.java:171)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.handleReadInitial(EngineWorker.java:1241)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.handleRead(EngineWorker.java:1205)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
        at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:817)
        ... 3 more
        Suppressed: java.lang.Exception: [engine/data#9]        [0x0109000000000003] streams=[consumeAt=0x00005258 (0x0000000000005258), produceAt=0x000054d8 (0x00000000000054d8)]
                at io.aklivity.zilla.runtime.engine@0.9.79/io.aklivity.zilla.runtime.engine.internal.registry.EngineWorker.doWork(EngineWorker.java:821)
                ... 3 more
```
**Expected behavior**

Arrive at this page, while trying to access `https://localhost:9090`

![Screenshot 2024-04-23 at 12 56 20 PM](https://github.com/aklivity/zilla/assets/6847653/f286a7ee-991a-455b-a8a8-15c2e5766868)

**Comment by jfallows** [comment]
Fixed by #976
